### ISSUE TITLE
Automatic command collection?

### ISSUE THREAD

**Issue by csachs** [facebookincubator/python-nubia#10]
At first seeing nubia, I was excited of what I believed an easy way to glue together a CLI application …
however after trying to run the example from the README (by the way, the line `cprint(f"Verbose? {}".format(ctx.verbose), "yellow")` contains a `SyntaxError` causing `f`) by attaching a 
```python
from nubia import Nubia
Nubia(name="example").run()
```
to the example snippet from the README, no custom commands were usable.

Now taking a look at the example files, I see that, apparently without a custom Plugin, nothing happens, and furthermore, the commands have to collected manually in that class.

Why is that the case? Was it deliberately decided against, or was it just not implemented? The decorator could just register `command`s (and if no particular selection is needed, all could be usable by default), reducing the barrier of using nubia.

**Comment by ylectric** [comment]
@csachs thanks for your suggestion!
You're right about the example, we've initially missed this in #8.

The good news are that we already the plan to support commands auto-discovery. Nubia lacks it due to historical reasons, but we definitely look forward to implementing it.

**Comment by AhmedSoliman** [comment]
Thank you @csachs for your message. We definitely has the automatic command discovery in plan. The plan we have in mind is different than what you described but the effect of it is pretty much the same.

I'm planning to ship that before we mark nubia ready for v1.0. Stay tuned.

**Comment by csachs** [comment]
Thanks for the clarifying responses. In that case it seems best to just wait :)

As another suggestion, I think having the name optional and have nubia auto-guess (e.g. based on script or module name) would be a nice feature. If someone is developing a large application, it's obviously fine to do some elaborate setup of nubia somewhere. But if someone just wants to quickly give one or a few functions a nice CLI (and nubia looks perfect for that!), the less 'unnecessary code' the better, imo.

**Comment by AhmedSoliman** [comment]
#38 introduces this as part of our prep to release 1.0

**Comment by AhmedSoliman** [comment]
Just to clarify, what I introduced in #38 is not exactly the same as @csachs proposed here. The user will need to import a python package (or more) that enclose all of the commands and pass the package to Nubia as an argument.
