### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by chassing** [facebookincubator/python-nubia#15]
please make a release with latest features (e.g. #7)

**Comment by dvx** [comment]
Heya folks, I would also appreciate a version bump (also interested in #7), lest I include the whole thing in my release.

**Comment by calebmarchent** [comment]
I plan to release once we are in the New Year, no later than end of,  w/c 7 Jan 2019.
I had hoped to nail 3.7 support before the new release but while I was able to solve the first reported issue, I revealed a number of unit test failures; so will need to leave that until a later release

**Comment by dvx** [comment]
Thanks for the update @calebmarchent -- Merry Christmas & Happy Holidays!

**Comment by calebmarchent** [comment]
Python Nubia 0.1b4 has now been uploaded to PyPi
