### ISSUE TITLE
TravisCI builds failing

### ISSUE THREAD

**Issue by calebmarchent** [facebookincubator/python-nubia#17]
https://travis-ci.com/facebookincubator/python-nubia/builds/94521692

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The command "pipenv install -d --system --three" failed and exited with 1 during .

**Comment by calebmarchent** [comment]
Something else weird here, TravisCI build history doesn't appear to match commit history.
Need to understand why there is a gap.

**Comment by calebmarchent** [comment]
I found a couple of articles on this issue, but am still not clear on the most reliable way forward so have posted a question on the Travis forums: https://travis-ci.community/t/travisci-support-for-pipenv/1436.

**Comment by calebmarchent** [comment]
Fixed

**Comment by y92lin** [comment]
> Fixed

How did you resolve this issue? I'm having the same problem
