### ISSUE TITLE
To replace FileHistory with InMemoryHistory

### ISSUE THREAD

**Issue by zhutony** [facebookincubator/python-nubia#23]
I have created my first ticket here before, but I forgot to thank you guys for the awesome work. It has worked very well even in its humble beta version!

My question today is about command history. For security/privacy reason, I need to use InMemoryHistory instead, but it looks like I'd have to change Nubia source code. I'm looking for any other possible ways without changing the source code. any suggestions? or does it make sense to make the command history configurable in Nubia?

**Comment by AhmedSoliman** [comment]
Thanks @zhutony for posting. I think it's a great idea to have this controllable from the Plugin so that developers get an opportunity to decide. I will send a pull request today.

**Comment by zhutony** [comment]
that's awesome, thanks @AhmedSoliman!

**Comment by AhmedSoliman** [comment]
The diff that adds the support is landing. The way this works is that you will have to supply an `nubia.internal.options.Options` object as an argument to `Nubia`

See `internal/options.py` you will find the property `persistent_history` and it's set to True by default.

Note that this adds a new dependency on `dataclasses` as it's not readily available in Python 3.6. When we move to 3.7 I will remove this dependency.

Let me know if this helps.

**Comment by zhutony** [comment]
yes, that's good enough for me. thank you so much for your quick response. really appreciate it.
