### ISSUE TITLE
Move to asyncio everywhere

### ISSUE THREAD

**Issue by AhmedSoliman** [facebookincubator/python-nubia#30]
After migrating to prompt-toolkit 2+ we should redefine the internal workflow around awaitables instead of plain-old function calls. This unblocks the work for background dispatch idea and make sure that users have a nice experience writing async commands first-level.

**Comment by adhaamehab** [comment]
@AhmedSoliman Can I work on this?

**Comment by ylectric** [comment]
@adhaamehab Please go ahead, although I think we've never actually defined what "everywhere" means :(

**Comment by adhaamehab** [comment]
Great :)
I'm assuming that everything means every async-able  code :D

**Comment by ddutt** [comment]
Any updates on this?

**Comment by AndreasBackx** [comment]
@ddutt not really. I think we could do this progressively when we need to. I think we would be open to accept any incoming PRs that add async.

**Comment by esciara** [comment]
Hi there. I submitted a PR at #78 . Looking forward to some feedback.

**Comment by AndreasBackx** [comment]
Should be addressed by #81.
