### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by sander76** [facebookincubator/python-nubia#50]
requirement levenshtein requires compiling on windows making installation very hard.

**Comment by AhmedSoliman** [comment]
Do you have suggestions in this case? do you think we should make Levenshtein optional?

**Comment by sander76** [comment]
I managed to install Levenshtein using the wheel provided here:

https://www.lfd.uci.edu/~gohlke/pythonlibs/

But I don't have a clue what Levenshtein does. So I don't know whether it is an option to make it optional ;-)

**Comment by AhmedSoliman** [comment]
Then we are good. Closing this :)

**Comment by sander76** [comment]
Well, having to manually install levenshtein severely minimizes usability of this library. So if it could be made optional that would make it much more usable in a win environment.

**Comment by ylectric** [comment]
@AhmedSoliman, I agree with @sander76 here and therefore I'm re-opening this.
Although we've never tested Nubia on Windows, I think we should at least remove any obvious blockers. Let me look at the alternatives.

**Comment by ylectric** [comment]
@sander76, I don't have access to Windows machine, could you please confirm that [jellyfish](https://github.com/jamesturk/jellyfish) installation is straightforward in your environment? 
A simple `pip install jellyfish` would suffice.

**Comment by sander76** [comment]
@ylectric Yes. Installs without any problem.

**Comment by ylectric** [comment]
@sander76, cool, thank you,
I'll send a PR to use jellyfish then.

**Comment by sander76** [comment]
No. Thank YOU.

**Comment by ylectric** [comment]
Quick update: I have two internal PRs that will switch Nubia to [jellyfish](https://github.com/jamesturk/jellyfish) once landed (hopefully by the end of the week).

**Comment by ylectric** [comment]
Fixed in fe65311.
