### ISSUE TITLE
Nubia doesn't recognize string-literals starting from digit

### ISSUE THREAD

**Issue by spuzirev** [facebookincubator/python-nubia#53]
Look at screenshot attached

![image](https://user-images.githubusercontent.com/1415234/59199095-07dbb680-8b8d-11e9-9b71-f05c492350b0.png)

**Comment by Zepheus** [comment]
String literals historically used to be quoted at all times in interactive mode. However, we decided to simplify both lists, dictionaries and strings to no longer require quotes in some cases.

Given the quotes are the "explicit" conversion to string, I am not sure whether it'll actually be worth to build a parser that can do both.

@AhmedSoliman any thoughts on this one?

**Comment by spuzirev** [comment]
1) This field is annotated as `List[str]`, there's completely no reason to try to parse it as numeric.
2) Token containing mix of digits and letters probably is a string literal and not a numeric literal.

**Comment by AhmedSoliman** [comment]
I think that this is a bug and should be fixed.

**Comment by toti1212** [comment]
I read this issue and tried reproduced with `super-command print-name firstname=` command. Reordering the precedences from `singles_values` in parser seems to work. 🤔
