### ISSUE TITLE
"Unknown Command ':help', Did you mean help? type :help to see all available commands"

### ISSUE THREAD

**Issue by advand** [facebookincubator/python-nubia#60]
Built-in help is available under `help`, not `:help` as indicated by the above message.

**Comment by AhmedSoliman** [comment]
Do you want to send a PR to fix the help message?

**Comment by fredxia** [comment]
Ok. I will create a PR. Thanks.

Fred

**Comment by David132639** [comment]
Looks like this was resolved by 313effa03c10cfb1c251b7e8d5f2aa6206849f10
