### ISSUE TITLE
Wrong args in io_loop.parse_and_evaluate() in start_interactive()

### ISSUE THREAD

**Issue by fredxia** [facebookincubator/python-nubia#61]
Hi,

There is extra argument for parse_and_evaluate() in this call in nubia/internal/nubia.py:

                print("> {}".format(command))
                ret = io_loop.parse_and_evaluate(sys.stdout, command)
 
"sys.stdout" should be removed.

Thanks.

**Comment by AhmedSoliman** [comment]
Good catch, do you want to send a PR to remove this or do you want me to send a fix instead?
