### ISSUE TITLE
.exe built with pyinstaller does not show commands

### ISSUE THREAD

**Issue by vecin2** [facebookincubator/python-nubia#65]
After importing nubia and create my commnads module with a simple command hello, I can run it  with `python example.py` and the hello command is prompted.

However if create a distribution using pyinstaller, when I run the example.exe, the hello command is not prompted anymore (only nubia commands are prompted)

I am assuming it will have to do with the way nubia  searches commands within the command package. But I've tried running pyinstaller with `--hidden-import path.to.my.command_module` and still got the same result

**Comment by vecin2** [comment]
Ill close as this issue as this is more related with the pyinstaller works:

Python nubia needs the commands source code at runtime , so it can be parsed and then generate the commands, agurments, etc. However pyinstaller does not add source files by default (it uses .pyc). 
I was able to get the commands to appear after including the commands package as data in pyinstaller (simply using --add-data flat, and having the source and target location being the same)

**Comment by dickens88** [comment]
@vecin2 I met the same issue, I want to package the script into a .exe with pyinstaller. cloud you please share the details you solve the problem?
