### ISSUE TITLE
can't extend example with self commands

### ISSUE THREAD

**Issue by BakinSergey** [facebookincubator/python-nubia#69]
Hi!
Great work! Can u help me with my little trouble?
I try to add my own command to the example and later I don't see it in the list of commands. (
i add this fn into example/commands/sample_commans.py:
@command
@argument("number", type=int)
async def twiced(number):
    "Calculates the triple of the input value"
    cprint("Input is {}".format(number))
    cprint("Type of input is {}".format(type(number)))
    cprint("{} * 2 = {}".format(number, number * 2))
    await asyncio.sleep(2)

in interactive:
(venv) sabrus@fly:~/GithubProjects/python-nubia$ python example/nubia_example.py
Logging to /tmp/nubia_example-k5zlddp5
sabrus> twiced

Unknown Command 'twiced', type :help to see all available commands

what i missed to do? 
in debug i see what twiced cmd is founded and handled, but at runtime cmd is absent...
Thank for your Job!

**Comment by AhmedSoliman** [comment]
Did you try adding `description` to your argument?
```
@command
@argument("number", type=int, description="an input number")
async def twiced(number):
    "Calculates the triple of the input value"
    ...
```

**Comment by BakinSergey** [comment]
yes, i try different trick, but no result (
even if i change code of example triple fn, and start new terminal session, i got prev fn behavior:
![image](https://user-images.githubusercontent.com/24735040/90237028-496c8f00-de2c-11ea-8a05-82ca3c5974f6.png)

**Comment by AhmedSoliman** [comment]
Can you push that code to some repository so I can take a look at it?

**Comment by BakinSergey** [comment]
no my_custom code! 
i just:
1. clone https://github.com/facebookincubator/python-nubia.git
2. make venv from requirements.txt
3. change 49line(screen) 
from:
cprint("{} * 3 = {}".format(number, number * 3))
to:
cprint("{} * 2 = {}".format(number, number * 2))
4. call  python example/nubia_example.py
