### ISSUE TITLE
can i change argparse arguments at runtime?

### ISSUE THREAD

**Issue by BakinSergey** [facebookincubator/python-nubia#70]
how do I make it work (at runtime):
```
from nubia import command, argument, context
...
@command
@argument("level", name='level', type=int, description='verbose level')
def change_verbose(level: int):
    "change verbose at runtime"
    ctx = context.get_context()
    ctx.set_verbose(level)

``` 
my question is: is it possible to change the startup parameters during execution?

**Comment by AndreasBackx** [comment]
If I understand correctly, you want to have a command `change_verbose` to change the verbosity in your cli application? You would need to store this state/configuration outside of your application and read that in every time your application starts. Though this seems to be out of the scope Nubia.

**Comment by BakinSergey** [comment]
some true, some not. 
First. If i saw STATUSBAR with Verbose=OFF....Why i can't change it at runtime? 
Second. Interactive mode as for me, mean that i can choose "mode of interactive", i.e change working mode, yeah, right, at rruntime...Verbose here is just for ex, in my app, i wanna have my specified DL modes...and as i understood - the statusbar at nubia as it now - just for printing some of args with which exec was called...

**Comment by AndreasBackx** [comment]
Sorry for the late reply. But I had another quick look and we seem to have a builtin command for this that you can use: `:verbose`. Have a look at the implementation here: https://github.com/facebookincubator/python-nubia/blob/master/nubia/internal/commands/builtin.py#L66-L89

**Comment by AndreasBackx** [comment]
Let me know if you have any more issues. I'll close it for now as we haven't heard back. 😊
