### ISSUE TITLE
Add pager to shell mode

### ISSUE THREAD

**Issue by ddutt** [facebookincubator/python-nubia#72]
When executing inside python-nubia, it'd be useful to have a pager to pause the display, much like less or more. People who're comfortable with the completions and support offered by nubia inside the nubia shell are uncomfortable typing the long command from bash and piping it through more.

It seems there's a pager support using prompt-toolkit, https://github.com/prompt-toolkit/pypager. Is it possible to incorporate this functionality into nubia? 

I'm willing to help.

**Comment by AhmedSoliman** [comment]
I'm not sure I understand how this will work exactly. Can you explain with an example?

**Comment by ddutt** [comment]
Sorry for the delay in responding. I implemented this within the app myself.

Essentially, when there's more than a screenful in the interactive mode, users want a way to get the equivalent of Unix's more (or less) command. Does that help?

**Comment by ddutt** [comment]
I implemented this in my app itself, instead of relying on nubia.
