### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by ddutt** [facebookincubator/python-nubia#73]
My project netenglabs/suzieq relies on nubia, but cannot use it via python packages due to infrequent releases. Would it be possible to get into a regular release cadence (into package upstream) even if all it has are bug fixes? The main benefit among other things is that I can stop relying on my fork of this repo. Thanks.

**Comment by AhmedSoliman** [comment]
I think we can set this up to be automated via Github Actions. Let me figure a way to make this happen.

**Comment by ddutt** [comment]
Any update on this ? I cannot release a PyPi package of my software because the version of nubia on PyPi is over a year old, and PyPi won't let me link to a github version. Thanks.

**Comment by AhmedSoliman** [comment]
I've just released 0.2b5 to pypi until we get that automated. Hope that helps.

**Comment by ddutt** [comment]
Yes!I managed to publish to PyPi with 0.2b5! Thank you, Dinesh
