### ISSUE TITLE
Nubia doesn't do anything

### ISSUE THREAD

**Issue by Hubro** [facebookincubator/python-nubia#77]
I want to create a CLI interface as an enhancement to an existing project.

I have placed my Nubia code in the module: `myproject/cli.py`.

When I try to execute the CLI using: `python -m myproject.cli`, nothing happens.

My example code:

```python3
from nubia import command, argument


@command
@argument(
    "event_type",
    description="The event type to trigger webhooks for",
    positional=True,
)
def trigger_webhooks(event_type: str) -> None:
    print("Success")
```

I don't want to execute the Python module directly (like `python3 myproject/cli.py` because, long story short, it messes with module paths and makes my application crash.

---

EDIT: I should have done some more testing before creating a bug report. It turns out I can't get Nubia to do anything no matter what I do. I have reduced my test file to the bare minimum:

```python3
#!/usr/bin/env python3

from nubia import command


@command
def trigger_webhooks() -> int:
    print("Success")

    return 0
```

I've marked the file as executable and I'm running `./cli.py`, nothing happens. The command exits with status code 0 and no output. Have I completely misunderstood something here?

I'm using CPython 3.9.1 with python-nubia 0.2b5.

**Comment by AhmedSoliman** [comment]
This is not enough to create a Nubia application. You need to have a main runner similar to the structure in the example application. Take a look at https://github.com/facebookincubator/python-nubia/blob/master/example/nubia_example.py for a working example.

**Comment by Hubro** [comment]
> This is not enough to create a Nubia application. You need to have a main runner similar to the structure in the example application. Take a look at https://github.com/facebookincubator/python-nubia/blob/master/example/nubia_example.py for a working example.

Ok, I see. That wasn't clear from the README :slightly_smiling_face: I would consider updating the README with a complete example.

Thanks!
