### ISSUE TITLE
Can't disable all built-in command

### ISSUE THREAD

**Issue by dickens88** [facebookincubator/python-nubia#80]
Hi ,

Is there anyway to disable built-in command, I tried the following method, but it seems some of the commands can be disable but some are not, eg `exit`.

```
invisable_executable_list = ['connect', 'exit', ':verbose']

....

    for cmd_abandoned in invisable_executable_list:
        if cmd_abandoned in cmdline._registry._completer.words:
            cmdline._registry._completer.words.remove(cmd_abandoned)
            cmdline._registry.get_all_commands_map().pop(cmd_abandoned)
```

I want to disable `exit` command, bcos my code need to use that word. many thanks

**Comment by AhmedSoliman** [comment]
I don't think there is any easy way to do that at the moment.

**Comment by dickens88** [comment]
got it, many thanks
